# Generated by Django 3.2.3 on 2021-05-20 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
