# Generated by Django 3.2.3 on 2021-05-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
